app = "CompanyRegisterPortal"

[build]
  build_command = "dotnet publish CompanyApi -c Release -o ./publish"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true