app = "company-reg"  # ← Changed to valid name
primary_region = "cdg"  # Paris region

# Remove ALL [build] section if present
# Fly.io will auto-detect Dockerfile

[http_service]
  internal_port = 8080
  force_https = true