app = "compnayregestrationportal"  # Lowercase, hyphens only

[build]
  builder = "paketobuildpacks/builder:dotnet-core"
  buildpacks = ["gcr.io/paketo-buildpacks/dotnet-core"]

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  PORT = "8080"  # .NET's default internal port

[http_service]
  internal_port = 8080
  force_https = true