# fly.toml
app = "your-app-name"  # Replace with your desired name (lowercase, hyphens)

[build]
  builder = "paketobuildpacks/builder:dotnet-core"
  buildpacks = ["gcr.io/paketo-buildpacks/dotnet-core"]

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true